use GMSQUARD
-- Create Database
--CREATE DATABASE GMSQUARD
--Create Table
--CREATE TABLE GMSTEAM(
--USERID INT IDENTITY(1,1),
--EMPNAME VARCHAR(50) NOT NULL,
--AGE INT NOT NULL,
--EMAIL VARCHAR(100) UNIQUE,
--CREATEDAT DATETIME DEFAULT GETDATE()
--);
--CREATE TABLE GMS_SALARY(
--USERID INT primary key identity (1,1),
--SALARY INT,
--CREATEDAT DATETIME DEFAULT GETDATE()
--)
--AGGEREGATE FUNCTION

SELECT COUNT(*) FROM GMSTEAM;
SELECT SUM(SALARY) FROM GMS_SALARY;
SELECT AVG(AGE) FROM GMSTEAM;

--STRING FUNCTION

SELECT UPPER('helo madhan')
SELECT LOWER('HELO MADHAN')
SELECT REPLACE('HEY MAN','WHAT HAPPEND','GNANA')

--DATE AND TIME FUNCTION
SELECT GETDATE();
SELECT DATEADD(YEAR,10,'2024-12-23') AS DATE
SELECT DATEADD(DAY,-5,GETDATE()) AS DAY
SELECT DATEADD(DAY, -DAY('2025-03-04'), '2025-03-04') AS LastDayPrevMonth;
SELECT FORMAT(GETDATE(), 'yyyy-MM-dd')
SELECT FORMAT(GETDATE(),'dd-MM-yyyy')
SELECT FORMAT(GETDATE(),'yyyy-dd-MM')
SELECT FORMAT(GETDATE(),'dd-MM-yyyy HH:mm:ss')
SELECT FORMAT(DATEADD(DAY, 10, GETDATE()), 'MMM dd, yyyy') AS TenDaysLater,FORMAT(ROUND(1234.5678, 2), 'N2') AS RoundedNumber
SELECT FORMAT(123456778.98,'N2')AS NUMBER 

--MATHEMATICAL FUNCTION
SELECT ABS(-12.5)
SELECT ROUND(233399.7678,0)
SELECT ROUND(6789.45689,2)

--CONVERSTION DATA TYPE
SELECT CAST(456 AS VARCHAR(15))
SELECT CONVERT(DATE, '2025-12-12', 23); 

---------------------------------------STORE PROCEDURE--------------------------------------
--CREATE TABLE TEAMMEMBERS(
--EMPLOYEEID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
--NAME NVARCHAR(200),
--AGE INT,
--DEPARTMENT NVARCHAR(50)
--);

--CREATE PROCEDURE MANAGETEAMS
--@ACTION VARCHAR(20), --DETERMINE OPERATION(INSERT, UPDATE, DELETE, SELECT)
--@EMPLOYEEID INT = NULL,  --REQUIRED FOR (UPDATE AND DELETE)
--@NAME NVARCHAR(200) = NULL,
--@AGE INT = NULL,
--@DEPARTMENT NVARCHAR(50)= NULL

--AS
--BEGIN
----INSERT OPERATION
--IF @ACTION ='INSERT'
--BEGIN
--INSERT INTO TEAMMEMBERS(NAME,AGE,DEPARTMENT)
--VALUES(@NAME,@AGE,@DEPARTMENT);
--END

----UPDATE OPERATION
--ELSE IF @ACTION='UPDATE'
--BEGIN
--UPDATE TEAMMEMBERS
--SET NAME=@NAME,AGE=@AGE,DEPARTMENT=@DEPARTMENT
--WHERE EMPLOYEEID=@EMPLOYEEID;
--END

----DELETE OPERATION
--ELSE IF @ACTION='DELETE'
--BEGIN
--DELETE FROM TEAMMEMBERS WHERE EMPLOYEEID=@EMPLOYEEID;
--END

----SELECT/RETRIVE OPERATION
--ELSE IF @ACTION='SELECT'
--BEGIN
--SELECT * FROM TEAMMEMBERS;
--END

--END;

----------------------------------------------------------------------------------------------

SELECT G.USERID,G.EMPNAME,G. AGE, G.EMAIL ,GS.SALARY FROM GMSTEAM G
LEFT OUTER JOIN GMS_SALARY GS ON (G.USERID =GS.USERID)
WHERE G.USERID=GS.USERID

--INSERT INTO GMSTEAM(empname,age,email) VALUES('Ashok',28,'ashok@gmail.com')
--insert into GMS_SALARY(salary)values(30)
select * from GMSTEAM
select * from gms_salary
SELECT * FROM TEAMMEMBERS
ALTER TABLE TEAMMEMBERS ADD USERID INT





